services:
  - type: web
    name: labubu-music
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update -y && apt-get upgrade -y
      apt-get install -y ffmpeg opus-tools
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python3 -m LabubuMusic
    autoDeploy: true

    envVars:
      API_ID: 
        value: 29448785
      API_HASH: 
        value: 599574f6aff0a09ebb76305b58e7e9c2
      BOT_TOKEN:
        sync: false
      MONGO_DB_URI: 
        value: mongodb+srv://pusers:nycreation@nycreation.pd4klp1.mongodb.net/?retryWrites=true&w=majority&appName=NYCREATION
      OWNER_ID:
        value: 7574330905
      OWNER_USERNAME:
        value: Matto_Owner
      BOT_USERNAME:
        value: LabubuMusicBot
      UPSTREAM_REPO:
        value: https://github.com/NoxxOP/LabubuMusic
      LOG_GROUP_ID:
        value: -1002321189618
      SUPPORT_GROUP:
        value: https://t.me/Laboobubots
      SUPPORT_CHANNEL:
        value: https://t.me/Laboobubots
      HEROKU_API_KEY:
        sync: false
      HEROKU_APP_NAME:
        sync: false
      GIT_TOKEN:
        sync: false
      STRING_SESSION:
        sync: false