services:
  - type: web
    name: labubu-music
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update -y && apt-get upgrade -y
      apt-get install -y ffmpeg opus-tools
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python3 -m LabubuMusic
    autoDeploy: true

    envVars:
      API_ID: 
        value: 35020744
      API_HASH: 
        value: 0b3d137e0309b92d43f82b13a24deae2
      BOT_TOKEN:
        sync: 8561351372:AAHMOO7tFeWxkDKeDlgtJuEups5F9s7GsmE
      MONGO_DB_URI: 
        value: mongodb+srv://matto_laado:@MonkeyFOrever567890@cluster0.q5dcvoq.mongodb.net/?appName=Cluster0
      OWNER_ID:
        value: -1003809861696
      OWNER_USERNAME:
        value: boobubots
      BOT_USERNAME:
        value: LabubuMusicBot
      UPSTREAM_REPO:
        value: https://github.com/Matto726/LabubuMusic
      LOG_GROUP_ID:
        value: -1002321189618
      SUPPORT_GROUP:
        value: https://t.me/Laboobubots
      SUPPORT_CHANNEL:
        value: https://t.me/Laboobubots
      HEROKU_API_KEY:
        sync: false
      HEROKU_APP_NAME:
        sync: false
      GIT_TOKEN:
        sync: false
      STRING_SESSION:
        sync: false
